# Generated by Django 5.0.1 on 2024-01-25 16:15

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_webpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AddField(
            model_name='webpost',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='webpost',
            name='image',
            field=models.ImageField(default='', upload_to='application/static/img/post'),
        ),
        migrations.AddField(
            model_name='webpost',
            name='photo_create',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='webpost',
            name='short_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='webpost',
            name='unique_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='webpost',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
