# Generated by Django 5.0.1 on 2024-01-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_webpost_content_webpost_created_date_webpost_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSubThemePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WebThemePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
