# Generated by Django 5.0.1 on 2024-01-25 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_websubthemepost_webthemepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpost',
            name='subtheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.websubthemepost'),
        ),
        migrations.AddField(
            model_name='webpost',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.webthemepost'),
        ),
    ]
